# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webpage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Legal Name')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone number')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('agentimage', models.CharField(default=None, max_length=300, validators=[webpage.validators.validateURL], verbose_name='Agent Badge Logo')),
                ('agentverifile', models.CharField(default=None, max_length=300, validators=[webpage.validators.validateURL], verbose_name='Agent verification file')),
                ('about', models.CharField(default=None, max_length=300, verbose_name='About')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('concern_id', models.IntegerField(blank=True, default=-1)),
                ('upvote_count', models.IntegerField(default=0)),
                ('isSolved', models.BooleanField(default=False)),
                ('submitted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('respond', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1000)),
                ('file_type', models.CharField(max_length=100)),
                ('url', models.CharField(default='', max_length=1000)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Legal Name(Optional)')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone number(Optional)')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address(Optional)')),
                ('reporterimg', models.CharField(blank=True, default='http://127.0.0.1:8000/static/images/default_avatar.png', max_length=300, validators=[webpage.validators.validateURL], verbose_name='Reporter Image(Optional)')),
                ('about', models.CharField(blank=True, max_length=300, null=True, verbose_name='About(Optional)')),
                ('historical_concern_count', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='concern',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Reporter'),
        ),
        migrations.AddField(
            model_name='concern',
            name='target_agent',
            field=models.ManyToManyField(to='webpage.Agent'),
        ),
    ]
